version: "3.9"

services:
  frontend:
    build: .
    container_name: esi-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      payment-service:
        condition: service_started
      ride-discovery-service:
        condition: service_started
    networks:
      - esi-network
    restart: unless-stopped
    environment:
      - VITE_GATEWAY_API_URL=${VITE_GATEWAY_API_URL:-http://localhost:8080}
