version: "3.9"

# Include individual service compose files
include:
  - backend/kafka/compose.yml
  - backend/api-gateway-service/docker-compose.yml
  - backend/payment-service/docker-compose.yml
  - backend/ride-discovery-service/docker-compose.yml
  - backend/auth-service/compose.yaml
  - frontend/docker-compose.yml

# Shared network for all services
networks:
  esi-network:
    driver: bridge
    name: esi-network
