# --- Spring Boot Application ---
server.port=8085
spring.application.name=profile

# --- Security ---
jwt.secret=${JWT_SECRET}

# --- Database Configuration ---
# If running locally via IDE (not Docker), it uses localhost.
# Inside Docker, the environment variables will override this.
spring.datasource.url=jdbc:postgresql://profile-postgres-db:5432/profile_db
spring.datasource.username=${PROFILE_DB_USER:default_user}
spring.datasource.password=${PROFILE_DB_PASSWORD:default_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Apache Kafka Configuration ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.admin.fail-fast=true
spring.kafka.admin.properties.request.timeout.ms=2000
spring.kafka.admin.properties.default.api.timeout.ms=2000

# --- Kafka Consumer Configuration ---
spring.kafka.consumer.group-id=profile-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# --- Kafka Producer Configuration ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
