spring.application.name=geolocation

# --- Custom JWT Configuration ---
# Must be provided by Docker/.env or environment variable
jwt.secret=b23be62e80435d3b061eb0b2cc2e655c7e056518b45a2f79839dd6e22ef86fe7
