spring:
  application:
    name: ride-discovery-service

server:
  port: ${PORT:8082}

clients:
  booking-service-url: ${BOOKING_SERVICE_URL:http://ride-booking-service:8080}
  review-service-url: ${REVIEW_SERVICE_URL:http://esi-review-service:8080}
  geolocation-service-url: ${GEOLOCATION_SERVICE_URL:http://geolocation-service:8080}
