@bookingUrl = http://localhost:8083
@paymentUrl = http://localhost:8081
@bookingId = f0000000-0000-0000-0000-000000000001

### Get all bookings
GET {{bookingUrl}}/bookings
Accept: */*

### Get individual booking
GET {{bookingUrl}}/bookings/{{bookingId}}
Accept: */*

### Submit payment
POST {{paymentUrl}}/payments
Accept: */*
Content-Type: application/json

{
  "bookingId": "{{bookingId}}",
  "payerId": "660e8400-e29b-41d4-a716-446655440001",
  "payeeId": "660e8400-e29b-41d4-a716-446655440001",
  "amount": 20,
  "currency": "EUR"
}
