spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/auth/**
        - id: profile-service-route
          uri: ${PROFILE_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/profiles/**
          filters:
            - StripPrefix=1
        - id: booking-rides-route
          uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/rides/**
          filters:
            - StripPrefix=1
        - id: booking-bookings-route
          uri: ${BOOKING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1
        - id: payment-service-route
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/payments,/api/payments/**
          filters:
            - StripPrefix=1
        - id: discovery-service-route
          uri: ${DISCOVERY_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/search/**
            - Method=GET
          filters:
            - StripPrefix=1
        - id: review-service-route
          uri: ${REVIEW_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/reviews/**
          filters:
            - StripPrefix=1
        - id: geolocation-service-route
          uri: ${GEOLOCATION_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/geocode,/api/reverse-geocode
            - Method=GET
          filters:
            - StripPrefix=1
        - id: validation-service-route
          uri: ${VALIDATION_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/validation/**
          filters:
            - StripPrefix=1

server:
  port: ${PORT:8080}
